name: "LuciePerrier"

services:
  database:
    image: postgres:17
    container_name: lucieperrier_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - lucieperrier_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: lucieperrier_pgadmin
    ports:
      - "15433:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin/

  redis:
    image: redis:alpine
    container_name: lucieperrier_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

volumes:
  lucieperrier_data:
  pgadmin_data:

networks:
  postgres-network:
    driver: bridge
